### ISSUE TITLE
Option to "see all posts from this user" for all users, not just the ones in moderation queue

### ISSUE THREAD

**Issue by karilyn** [thestokelist/stokelistclient#37]
I'd love to be able to see all posts from a user and ban that email address when I click on the post in the main feed. Right now we can only do that if it's in the mod queue. Thanks!

**Comment by lukenorman** [comment]
@karilyn Where do you want the link - on the page where you're viewing the post (perhaps an admin link near the 'report post' button? Or next to the edit/delete buttons in the main feed?

**Comment by karilyn** [comment]
On the page where you're viewing the post is great, right by the admin link. Would be handy to find repeat offenders, haha. Thanks!

**Comment by lukenorman** [comment]
@karilyn This is live on prod now
